### PR TITLE
replace application_status route

### PR DESCRIPTION
**Pull request by mackfoggia**
This is an update to the application_status route to include status and description in the response and check for name instead of human-readable passphrase.

### CODE REVIEW

**Comment by ShatteredFortress** [comment]
Looks great, only thing I am curious about is using the first page method. Can we guarantee the user will be on the first page?

**Comment by mackfoggia** [comment]
> Looks great, only thing I am curious about is using the first page method. Can we guarantee the user will be on the first page?

By default the first page can be up to 100 records I believe, but in our current iteration the select should really only return one or zero records. If it returns more than one record than there were more than one matches for that name/dob and that case isn't covered by mvp.

**Comment by ShatteredFortress** [comment]
Oh okay I see now, your not having to parse through the records. By filtering you are able to just pull out the one record so first page will only ever have, one record

**Review by ShatteredFortress — APPROVED** [review]
Thanks for clarifying, looks great!

**Pull request merged**
